services:
  catalog-mongo:
    image: mongo
    container_name: catalog-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog-mongo:27017"
    depends_on: 
    - catalog-mongo
  basket-api:
    container_name: basket-api
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    ports:
      - 8081:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket-redis:6379"
    depends_on:
     - basket-redis
  basket-redis:
    image: redis:alpine
    restart: always
    container_name: basket-redis
    ports:
      - 6379:6379
  discount-postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  discount-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@abc.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    depends_on:
     - discount-postgres
  discount-api:
    container_name: discount-api
    build:
      context: .
      dockerfile: Discount.Api/Dockerfile
    ports:
      - 8082:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DataSettings:ConnectionString=Server=discount-postgres;Port=5432;Database=DiscountDb;User Id=admin;Password=admin"
    depends_on:
     - discount-postgres
     - discount-pgadmin
volumes:
  mongo_data:
  postgres_data:
  pgadmin_data: