

version: '3.4'

services:
  catalog-mongo:
    image: mongo
    container_name: catalog-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog-mongo:27017"
    depends_on: 
    - catalog-mongo
volumes:
  mongo_data: