services:
  catalog-mongo:
    image: mongo
    container_name: catalog-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog-mongo:27017"
    depends_on: 
    - catalog-mongo
  basket-api:
    container_name: basket-api
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    ports:
      - 8081:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket-redis:6379"
    depends_on:
     - basket-redis
  basket-redis:
    image: redis:alpine
    restart: always
    container_name: basket-redis
    ports:
      - 6379:6379
volumes:
  mongo_data: